#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require(__DIR__ . '/components/socket/SocketApplication.php');

$config = require __DIR__ . '/config/socket.php';

$application = new \app\components\socket\SocketApplication($config);
$exitCode = $application->run();
exit($exitCode);
